### ISSUE TITLE
Bug:V3.0.1.9 Directory Traversal Vulnerability

### ISSUE THREAD

**Issue by Richard1266** [jetiben/jtbc#10]
There is a Directory Traversal vulnerability in your latest version of the CMS v3.0.1.9
Download link: "https://download.jtbc.cn/php/3.0/PHP_JTBC_CMS.C.zip"
In the JTBC(PHP)v3.0.1.9\common\incfiles\jtbc.php, No filtering for input ../:
![1](https://user-images.githubusercontent.com/32863218/56720427-654eac00-6775-11e9-8fd6-49cb8bb56232.png)
![2](https://user-images.githubusercontent.com/32863218/56720435-6aabf680-6775-11e9-8c5f-2e941813a6cc.png)
Vulnerability trigger point:
http://www.jtbc.cn/console/#/console/file/manage.php?type=list
1、Log in as admin
![1](https://user-images.githubusercontent.com/32863218/56720693-f3c32d80-6775-11e9-8f42-4ffdafe7f77d.png)
2、Choose this part
![2](https://user-images.githubusercontent.com/32863218/56720703-f9207800-6775-11e9-8248-a583964608d4.png)
3、Capture the package change path and add files
![6](https://user-images.githubusercontent.com/32863218/56720815-35ec6f00-6776-11e9-8a70-796dd5d91f44.png)
![3](https://user-images.githubusercontent.com/32863218/56720824-3a188c80-6776-11e9-86ff-0fd902dbfdfd.png)
![4](https://user-images.githubusercontent.com/32863218/56720832-3f75d700-6776-11e9-9aa9-3e3b07661a36.png)
![5](https://user-images.githubusercontent.com/32863218/56720869-4ef52000-6776-11e9-99ef-313a2b1c0ce8.png)
![7](https://user-images.githubusercontent.com/32863218/56720877-54526a80-6776-11e9-9559-a3af59551037.png)
4、View the system file and found the file that was just built
![8](https://user-images.githubusercontent.com/32863218/56720922-69c79480-6776-11e9-8d7c-104e7d6aa847.png)
Fix:
In the file /common/incfiles/jtbc.php, filter the input '../'.

**Comment by jetiben** [comment]
您好，我们认为这并不是一个问题，服务器既然没有禁止PHP对于此目录的写入权限，那使用文件管理越过网站根目录写入文件夹并不是什么问题。禁止跨目录是服务器用户权限需要考虑的，而不是PHP需要考虑的。因为文件管理的权限非常大，它可以直接修改PHP文件，因此源码内禁止跨出网站根目录也毫无意义，因为用户也可以直接改写PHP。
