### ISSUE TITLE
JTBC 3.0.1.9(PHP) Unrestricted Upload of File with Dangerous Type

### ISSUE THREAD

**Issue by tr0uble-mAker** [jetiben/jtbc#15]
In JTBC 3.0.1.9（PHP）http://127.0.0.1/jtbc3.0.1.9/console/#/console/file/manage.php?type=list
![image](https://user-images.githubusercontent.com/71172892/130275505-d6b64ef8-87e9-41ea-8c64-881d2a9a1da6.png)
An attacker can upload dangerous PHP files to gain server privileges
![image](https://user-images.githubusercontent.com/71172892/130276084-2aa1d9da-82f7-430f-aa75-f5fe6c0f0794.png)
If the attacker uploads the 1.php file, the content is as above
When we visit 1.php just uploaded under the root directory of the website，we can see that the PHP file is parsed
![image](https://user-images.githubusercontent.com/71172892/130276212-7290c1fe-de33-4dbf-bd38-aba5ff30cbf8.png)
This allows an attacker to gain control of the server.As shown in the figure below, the attacker has obtained the webshell permission of the server
![image](https://user-images.githubusercontent.com/71172892/130276575-fdf2929d-08ed-4405-886f-00edcfcd2814.png)
Allowing any type of file to be uploaded to the server is undoubtedly a dangerous operation!!!

**Comment by jetiben** [comment]
再次说明：文件管理是一个模块，这个模块可以管理所有的文件（含PHP文件）。漏洞或者威胁应该是在匿名状态下才能称之为漏洞，文件管理属于后台管理，必须经过登录之后才有权限上传，拥有文件管理后相当于实际上具备了全部权限，这个情况可能在当一个管理员角色仅具备文件管理时，可能会有歧义，但这个歧义其实在其他各种场景中也会发生。因为你具备文件管理，文件管理的功能就是管理文件，PHP本身也是文件，整个网站的功能又基于PHP来实现，因此本质上属于最高级管理员。
