### ISSUE TITLE
Bug: file upload Vulnerability

### ISSUE THREAD

**Issue by fakerrr** [jetiben/jtbc#6]
There is an file upload vulnerability in your latest version of the CMS v3

In http://127.0.0.1/console/#/console/file/manage.php?type=list，upload the file
![image](https://user-images.githubusercontent.com/15666994/50756221-704d0180-1296-11e9-9435-ff7728435422.png)

document content ：
![image](https://user-images.githubusercontent.com/15666994/50756325-c8840380-1296-11e9-91a7-6d746ea0831d.png)

![image](https://user-images.githubusercontent.com/15666994/50756458-47793c00-1297-11e9-93ed-a9a64a868687.png)

2.Steps To Reproduce:
Open below URL in browser which supports flash.
url:http://127.0.0.1/console/#/console/file/manage.php?type=list;   upload webshell.php
exp:http://127.0.0.1/webshell.php  postdata:a=phpinfo();

Fix:

1. Verify the file name suffix and limit the uploading (php, jsp, aspx) scripts.
2. Set the upload whitelist, only allow uploading whitelist (jpg, png, gif) and other file types.
3 Set file storage directory permissions, prohibit file upload directory for script parsing.

**Comment by webtsp** [comment]
Hello,

This file management is a function of the background CMS. Its function is to upload any file, just like the website control panel, such as CPANEL can modify any file on the server, as long as this function does not break the permission authentication, ie: any user is It can be uploaded without login, so it can be considered a vulnerability.
