### ISSUE TITLE
上传文件移动异常，请确认上传目录权限或有没有其他进程将文件锁定

### ISSUE THREAD

**Issue by zhai-conan** [jetiben/jtbc#7]
https://github.com/jetiben/jtbc/blob/34d2d0a1d0581385a0b7e650e49c9ba9bf530b5f/php/v3.0(C)/common/incfiles/lib/jtbc/universal/upload.inc.php#L249

这里打开了上传的临时图片temp.tmp，在接下来的 fclose($chunkHandle) 处写入了图片内容，之后没有关闭文件的操作 fclose($fpTemp),从而引起 文件锁定的提示。

**Comment by jetiben** [comment]
谢谢您的提醒，确实漏了关闭操作。但大多数时候，文件不能移动被锁定可能的情况是本机安装了杀毒软件，比如360等导致的。

**Comment by zhai-conan** [comment]
我也没有经过太多测试，只是我本机在关闭杀毒软件后还是提示错误。才一步一步发现了文件移动和重命名失败的。但是在服务器上却是正常的。
