### ISSUE TITLE
建议加上对 decimal  类型的支持 

### ISSUE THREAD

**Issue by zhai-conan** [jetiben/jtbc#8]
https://github.com/jetiben/jtbc/blob/5be9523b1f02457a5a404b13cec71d597dd96c6d/php/v3.0(C)/common/incfiles/lib/jtbc/sql.inc.php#L265

建议加上 对 decimal  类型的支持

**Comment by jetiben** [comment]
这个类型并不常用呢，如果自身需要可以自己修改代码，一般类似金额的数据库字段现在一般设置为int，以分为单位，decimal这个类型一般用在比较专业的系统内。

**Comment by zhai-conan** [comment]
谢谢，了解了。
